//
// Created by david on 02/06/2022.
//

#ifndef PROYECTO_GM_EKF_PHD_SIMULATE_MEASUREMENTS_H
#define PROYECTO_GM_EKF_PHD_SIMULATE_MEASUREMENTS_H

#define NUM_F 10
#define NUM 30000

void GM_EKF_PHD_Simulate_Measurements(void);


#endif //PROYECTO_GM_EKF_PHD_SIMULATE_MEASUREMENTS_H
