//
// Created by david on 19/05/2022.
//

#ifndef PROYECTO_GM_EKF_PHD_SIMULATE_INITIALISE_H
#define PROYECTO_GM_EKF_PHD_SIMULATE_INITIALISE_H

#define NUM_F 10
#define NUM 30000

void GM_EKF_PHD_Simulate_Initialise(void);

#endif //PROYECTO_GM_EKF_PHD_SIMULATE_INITIALISE_H
