//
// Created by david on 19/06/2022.
//

#ifndef PROYECTO_GM_PHD_CONSTRUCT_UPDATE_COMPONENTS_H
#define PROYECTO_GM_PHD_CONSTRUCT_UPDATE_COMPONENTS_H

#define NUM_F 10
#define NUM 30000

void GM_PHD_Construct_Update_Components(void);


#endif //PROYECTO_GM_PHD_CONSTRUCT_UPDATE_COMPONENTS_H
